In [1]:
doc1 = 'New Chelsea manager Graham Potter has penned a farewell letter to the fans of his former club Brighton and Hove Albion asking for forgiveness for his abrupt departure and hoping they understood his reasons'
doc2 = 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country'
doc3 = 'A large satellite launching to space tomorrow could become brighter than any other object in the night sky except the moon raising concerns about its impact on astronomy'

In [2]:
docs = [doc1, doc2, doc2]
docs

['New Chelsea manager Graham Potter has penned a farewell letter to the fans of his former club Brighton and Hove Albion asking for forgiveness for his abrupt departure and hoping they understood his reasons',
 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country',
 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country']

In [3]:
# finding unique terms from the corpus
uni_terms = {term for doc in docs for term in doc.split()}
uni_terms

{'Albion',
 'Brighton',
 'COVID-19',
 'Chelsea',
 'Government',
 'Graham',
 'Hove',
 'New',
 'Potter',
 'The',
 'Union',
 'a',
 'abrupt',
 'accelerating',
 'and',
 'asking',
 'club',
 'committed',
 'country',
 'departure',
 'expanding',
 'fans',
 'farewell',
 'for',
 'forgiveness',
 'former',
 'has',
 'his',
 'hoping',
 'is',
 'letter',
 'manager',
 'of',
 'pace',
 'penned',
 'reasons',
 'scope',
 'the',
 'they',
 'throughout',
 'to',
 'understood',
 'vaccination'}

#### TF matrix

In [4]:
# constructing term-document index
doc_trm_matrix = {}

for term in uni_terms:
    doc_trm_matrix[term] = []
    
    for doc in docs:
        if term in doc:
            doc_trm_matrix[term].append(1)
        else:
            doc_trm_matrix[term].append(0)
            
doc_trm_matrix

{'reasons': [1, 0, 0],
 'accelerating': [0, 1, 1],
 'Graham': [1, 0, 0],
 'hoping': [1, 0, 0],
 'and': [1, 1, 1],
 'Hove': [1, 0, 0],
 'the': [1, 1, 1],
 'farewell': [1, 0, 0],
 'they': [1, 0, 0],
 'Chelsea': [1, 0, 0],
 'committed': [0, 1, 1],
 'vaccination': [0, 1, 1],
 'expanding': [0, 1, 1],
 'scope': [0, 1, 1],
 'Potter': [1, 0, 0],
 'is': [1, 1, 1],
 'of': [1, 1, 1],
 'throughout': [0, 1, 1],
 'has': [1, 0, 0],
 'Government': [0, 1, 1],
 'COVID-19': [0, 1, 1],
 'Brighton': [1, 0, 0],
 'abrupt': [1, 0, 0],
 'penned': [1, 0, 0],
 'understood': [1, 0, 0],
 'former': [1, 0, 0],
 'to': [1, 1, 1],
 'club': [1, 0, 0],
 'Albion': [1, 0, 0],
 'New': [1, 0, 0],
 'his': [1, 0, 0],
 'a': [1, 1, 1],
 'The': [0, 1, 1],
 'forgiveness': [1, 0, 0],
 'manager': [1, 0, 0],
 'fans': [1, 0, 0],
 'departure': [1, 0, 0],
 'country': [0, 1, 1],
 'pace': [0, 1, 1],
 'asking': [1, 0, 0],
 'Union': [0, 1, 1],
 'letter': [1, 0, 0],
 'for': [1, 0, 0]}

In [7]:
# bitwise AND contruct on the queries
import numpy as np

doc_array = np.array(docs, dtype='object')

v1 = np.array(doc_trm_matrix['vaccination'])
v2 = np.array(doc_trm_matrix['expanding'])
v3 = np.array(doc_trm_matrix['throughout'])
v4 = np.array(doc_trm_matrix['scope'])
v5 = np.array(doc_trm_matrix['a'])
v6 = np.array(doc_trm_matrix['to'])
v7 = np.array(doc_trm_matrix['is'])
print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
print(v6)Albion
print(v7)
print('-------')
     
v = v1 & v2 & v3 & v4 & v5 & v6 & v7
print(v)

[0 1 1]
[0 1 1]
[0 1 1]
[0 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
-------
[0 1 1]


In [8]:
# finding matching documents from the corpus.
[doc for doc in v * doc_array if doc]

['The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country',
 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country']

In [9]:
# bitwise OR construct on the queries
v1 = np.array(doc_trm_matrix['farewell'])
v2 = np.array(doc_trm_matrix['Chelsea'])
v3 = np.array(doc_trm_matrix['COVID-19'])
v4 = np.array(doc_trm_matrix['Albion'])
v5 = np.array(doc_trm_matrix['departure'])

print(v1)
print(v2)
print(v3)
print(v4)
print(v5)
print('--------')
v = v1 | v2 | v3 | v4 | v5
print(v)

[1 0 0]
[1 0 0]
[0 1 1]
[1 0 0]
[1 0 0]
--------
[1 1 1]


In [10]:
# finding matching documents from the corpus.
[doc for doc in v * doc_array if doc]

['New Chelsea manager Graham Potter has penned a farewell letter to the fans of his former club Brighton and Hove Albion asking for forgiveness for his abrupt departure and hoping they understood his reasons',
 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country',
 'The Union Government is committed to accelerating the pace and expanding the scope of COVID-19 vaccination throughout the country']

#### inverted matrix

In [12]:
# constructing an inverted index
inverted_index = {}

for i, doc in enumerate(docs):
    for term in doc.split():
        if term in inverted_index:
            inverted_index[term].add(i)
        else:
            inverted_index[term] = {i}
            
            
inverted_index

{'New': {0},
 'Chelsea': {0},
 'manager': {0},
 'Graham': {0},
 'Potter': {0},
 'has': {0},
 'penned': {0},
 'a': {0},
 'farewell': {0},
 'letter': {0},
 'to': {0, 1, 2},
 'the': {0, 1, 2},
 'fans': {0},
 'of': {0, 1, 2},
 'his': {0},
 'former': {0},
 'club': {0},
 'Brighton': {0},
 'and': {0, 1, 2},
 'Hove': {0},
 'Albion': {0},
 'asking': {0},
 'for': {0},
 'forgiveness': {0},
 'abrupt': {0},
 'departure': {0},
 'hoping': {0},
 'they': {0},
 'understood': {0},
 'reasons': {0},
 'The': {1, 2},
 'Union': {1, 2},
 'Government': {1, 2},
 'is': {1, 2},
 'committed': {1, 2},
 'accelerating': {1, 2},
 'pace': {1, 2},
 'expanding': {1, 2},
 'scope': {1, 2},
 'COVID-19': {1, 2},
 'vaccination': {1, 2},
 'throughout': {1, 2},
 'country': {1, 2}}

In [13]:
# creating posting list for the terms
posting_list = inverted_index['committed']
posting_list

{1, 2}

In [14]:
# performing boolean operations on posting lists
def or_postings(posting1, posting2):
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):
        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            result.append(posting2[p2])
            p2 += 1
        else:
            result.append(posting1[p1])
            p1 += 1
    while p1 < len(posting1):
        result.append(posting1[p1])
        p1 += 1
    while p2 < len(posting2):
        result.append(posting2[p2])
        p2 += 1
    return result

In [15]:
pl_1 = list(inverted_index['committed'])
pl_2 = list(inverted_index['and'])
or_postings(pl_1, pl_2)

[0, 1, 2]

In [16]:
def and_postings(posting1, posting2):
    p1 = 0
    p2 = 0
    result = list()
    while p1 < len(posting1) and p2 < len(posting2):
        if posting1[p1] == posting2[p2]:
            result.append(posting1[p1])
            p1 += 1
            p2 += 1
        elif posting1[p1] > posting2[p2]:
            p2 += 1
        else:
            p1 += 1
    return result

In [17]:
pl_1 = list(inverted_index['of'])
pl_2 = list(inverted_index['expanding'])
and_postings(pl_1, pl_2)

[1, 2]